/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.6.2
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum AnnotationType {
    BOOL = 0,
    BYTES = 1,
    I16 = 2,
    I32 = 3,
    I64 = 4,
    DOUBLE = 5,
    STRING = 6
}
export const CLIENT_SEND: string = "cs";
export const CLIENT_RECV: string = "cr";
export const SERVER_SEND: string = "ss";
export const SERVER_RECV: string = "sr";
export const WIRE_SEND: string = "ws";
export const WIRE_RECV: string = "wr";
export const CLIENT_SEND_FRAGMENT: string = "csf";
export const CLIENT_RECV_FRAGMENT: string = "crf";
export const SERVER_SEND_FRAGMENT: string = "ssf";
export const SERVER_RECV_FRAGMENT: string = "srf";
export const CLIENT_ADDR: string = "ca";
export const SERVER_ADDR: string = "sa";
